----------------------------------------------------------------------------------------------------
-- SQL file generated by generator.py with 50 data rows.
----------------------------------------------------------------------------------------------------

\set ON_ERROR_STOP true

INSERT INTO TransaccionTGR(id_persona, numero_repertorio, timestamp_recepcion, monto, estado_transaccion, ingreso, estado_TGR) VALUES
('18788857-3', '2018-1', '2005-12-31', 23308, 'ingresado', True, 'esperando');
