----------------------------------------------------------------------------------------------------
-- SQL file generated by generator.py with 50 data rows.
----------------------------------------------------------------------------------------------------

\set ON_ERROR_STOP true

INSERT INTO TransaccionTGR(folio, id_persona, numero_repertorio, timestamp_recepcion, monto, estado_transaccion, fecha_aprobacion, ingreso, estado_TGR) VALUES
('1','18788857-3', '1234',  '2005-12-31', 23308, 'ingresado', null, True, 'esperando');
